project:
  type: website
  render: 
    - "*.qmd"
    - "!todo/*"
    - "!archive_2425/*"
  output-dir: ../docs/2526/labs2011211-2015-101519918-61518-1-16189265/

website:
  title: "DAPR3 Lab Exercises"
  navbar: 
    background: primary
    search: true
    left:
      - text: "Multi-level Models"
        menu: 
          - 01ex.qmd
          - 02ex.qmd
          - 03ex.qmd
          - 04ex.qmd
          - 05ex.qmd
      - text: "Measurement & Factor Analysis"
        menu: 
          - 07ex.qmd
          - 08ex.qmd
          - 09ex.qmd
          - 10ex.qmd

format:
  html:
    page-layout: full
    toc: true
    toc_float: true
    theme: 
      - united
      - assets/style-labs.scss
    include-in-header: 
      - "assets/toggling.html"
      - text: |
          <link rel="stylesheet" href="https://uoepsy.github.io/assets/css/ccfooter.css" />
    link-citations: true
    number-sections: false
    code-copy: true


